package com.iota.campusX.ui.theme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

val primaryLight = Color(0xFF4C68D5)
//val primaryLight = Color(0xFF304EBB)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF4C68D5)
val onPrimaryContainerLight = Color(0xFFF5F4FF)
val secondaryLight = Color(0xFF535C87)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC3CCFE).copy(alpha = 0.2f)
val onSecondaryContainerLight = Color(0xFF4C5680)
val tertiaryLight = Color(0xFF89348F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFA54EAA)
val onTertiaryContainerLight = Color(0xFFFFF3FA)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFFFFF)
//val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1A1B22)
//val surfaceLight = Color(0xFFFBF8FF)
val surfaceLight = Color(0xFFF8F8F8)
val onSurfaceLight = Color(0xFF1A1B22)
val surfaceVariantLight = Color(0xFFE1E1F2)
val onSurfaceVariantLight = Color(0xFF444653).copy(alpha = 0.6f)
val outlineLight = Color(0xFFC5C5D5).copy(alpha = 0.6f)
val outlineVariantLight = Color(0xFFC5C5D5).copy(alpha = 0.4f)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3037)
val inverseOnSurfaceLight = Color(0xFFF1F0F9)
val inversePrimaryLight = Color(0xFFB8C4FF)
val surfaceDimLight = Color(0xFFDAD9E3)
val surfaceBrightLight = Color(0xFFFBF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F2FC)
val surfaceContainerLight = Color(0xFFEEEDF7)
val surfaceContainerHighLight = Color(0xFFE8E7F1)
val surfaceContainerHighestLight = Color(0xFFE3E1EB)

val primaryLightMediumContrast = Color(0xFF002A92)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF4865D1)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF2A345C)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF616B96)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF61066A)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFA14AA6)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFBF8FF)
val onBackgroundLightMediumContrast = Color(0xFF1A1B22)
val surfaceLightMediumContrast = Color(0xFFFBF8FF)
val onSurfaceLightMediumContrast = Color(0xFF101117)
val surfaceVariantLightMediumContrast = Color(0xFFE1E1F2)
val onSurfaceVariantLightMediumContrast = Color(0xFF333542)
val outlineLightMediumContrast = Color(0xFF50525F)
val outlineVariantLightMediumContrast = Color(0xFF6A6C7A)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2F3037)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF1F0F9)
val inversePrimaryLightMediumContrast = Color(0xFFB8C4FF)
val surfaceDimLightMediumContrast = Color(0xFFC6C5CF)
val surfaceBrightLightMediumContrast = Color(0xFFFBF8FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF4F2FC)
val surfaceContainerLightMediumContrast = Color(0xFFE8E7F1)
val surfaceContainerHighLightMediumContrast = Color(0xFFDDDCE5)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD2D1DA)

val primaryLightHighContrast = Color(0xFF00217A)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF1D3EAB)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF202A51)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF3D4770)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF52005A)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF77237F)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFBF8FF)
val onBackgroundLightHighContrast = Color(0xFF1A1B22)
val surfaceLightHighContrast = Color(0xFFFBF8FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE1E1F2)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF292B38)
val outlineVariantLightHighContrast = Color(0xFF464855)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2F3037)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFB8C4FF)
val surfaceDimLightHighContrast = Color(0xFFB8B8C1)
val surfaceBrightLightHighContrast = Color(0xFFFBF8FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF1F0F9)
val surfaceContainerLightHighContrast = Color(0xFFE3E1EB)
val surfaceContainerHighLightHighContrast = Color(0xFFD4D3DD)
val surfaceContainerHighestLightHighContrast = Color(0xFFC6C5CF)

//-------------------------------------------DARK COLOR------------------------------------------------------

val primaryDark = Color(0xFF4C68D5)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF4C68D5)
val onPrimaryContainerDark = Color(0xFFF5F4FF)
val secondaryDark = Color(0xFFBBC4F5)
val onSecondaryDark = Color(0xFF242E56)
//val secondaryContainerDark = Color(0xFF3B446E)
val secondaryContainerDark = Color(0xFF1F222A)
val onSecondaryContainerDark = Color(0xFFA9B3E3)
val tertiaryDark = Color(0xFFFFA9FF)
val onTertiaryDark = Color(0xFF590062)
val tertiaryContainerDark = Color(0xFFA54EAA)
val onTertiaryContainerDark = Color(0xFFFFF3FA)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF181A20)
//val onBackgroundDark = Color(0xFFE3E1EB)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF1F222A)
//val surfaceDark = Color(0xFF12131A)
val onSurfaceDark = Color(0xFFE3E1EB)
val surfaceVariantDark = Color(0xFF141515)
//val surfaceVariantDark = Color(0xFF444653)
val onSurfaceVariantDark = Color(0xFFC5C5D5)
val outlineDark = Color(0xFF444653).copy(alpha = 0.5f)
val outlineVariantDark = Color(0xFF444653)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E1EB)
val inverseOnSurfaceDark = Color(0xFF2F3037)
val inversePrimaryDark = Color(0xFF3855C2)
val surfaceDimDark = Color(0xFF12131A)
val surfaceBrightDark = Color(0xFF383940)
val surfaceContainerLowestDark = Color(0xFF0D0E14)
val surfaceContainerLowDark = Color(0xFF1A1B22)
val surfaceContainerDark = Color(0xFF1E1F26)
val surfaceContainerHighDark = Color(0xFF292A31)
val surfaceContainerHighestDark = Color(0xFF33343C)

val primaryDarkMediumContrast = Color(0xFFD5DAFF)
val onPrimaryDarkMediumContrast = Color(0xFF001C6B)
val primaryContainerDarkMediumContrast = Color(0xFF6E89F8)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFD5DAFF)
val onSecondaryDarkMediumContrast = Color(0xFF19234A)
val secondaryContainerDarkMediumContrast = Color(0xFF858EBC)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFCDFB)
val onTertiaryDarkMediumContrast = Color(0xFF47004F)
val tertiaryContainerDarkMediumContrast = Color(0xFFC96ECD)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF12131A)
val onBackgroundDarkMediumContrast = Color(0xFFE3E1EB)
val surfaceDarkMediumContrast = Color(0xFF12131A)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF444653)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDBDBEB)
val outlineDarkMediumContrast = Color(0xFFB0B1C0)
val outlineVariantDarkMediumContrast = Color(0xFF8E8F9E)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE3E1EB)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF292A31)
val inversePrimaryDarkMediumContrast = Color(0xFF1B3DAA)
val surfaceDimDarkMediumContrast = Color(0xFF12131A)
val surfaceBrightDarkMediumContrast = Color(0xFF43444C)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF06070D)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1C1D24)
val surfaceContainerDarkMediumContrast = Color(0xFF26272F)
val surfaceContainerHighDarkMediumContrast = Color(0xFF313239)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C3D45)

val primaryDarkHighContrast = Color(0xFFEEEFFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFB2C0FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF00072D)
val secondaryDarkHighContrast = Color(0xFFEEEFFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB7C0F1)
val onSecondaryContainerDarkHighContrast = Color(0xFF00072D)
val tertiaryDarkHighContrast = Color(0xFFFFEAFA)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFEA2FF)
val onTertiaryContainerDarkHighContrast = Color(0xFF1B001F)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF12131A)
val onBackgroundDarkHighContrast = Color(0xFFE3E1EB)
val surfaceDarkHighContrast = Color(0xFF12131A)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF444653)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEEEFFF)
val outlineVariantDarkHighContrast = Color(0xFFC1C1D1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE3E1EB)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF1B3DAA)
val surfaceDimDarkHighContrast = Color(0xFF12131A)
val surfaceBrightDarkHighContrast = Color(0xFF4F4F57)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1E1F26)
val surfaceContainerDarkHighContrast = Color(0xFF2F3037)
val surfaceContainerHighDarkHighContrast = Color(0xFF3A3B42)
val surfaceContainerHighestDarkHighContrast = Color(0xFF46464E)

//val DarkTheme_Black = Color(0xFF181A20) // Used for text/Icon color
val DarkTheme_LightBlack = Color(0xFF1F222A)

val DarkTheme_Gray = Color(0xCC838B98)


//Light Theme Color


val LightTheme_Blue = Color(0xCC4C68D5) //Used for button color
val LightTheme_Black = Color(0xFF181A20) // Used for text/Icon color
val LightTheme_Gray = Color(0xCCE5E5E5) // Used for unselected items color or icons
val LightTheme_LightGray = Color(0xFFF5F5F5) // Used for unselected items color or icons
val LightTheme_DarkGray = Color(0xCC838B98) // Used for unselected items color or icons
val LightTheme_White = Color(0xFFFFFFFF) // Used for background color


val Primary = Color(0xFF3750F7)


val LightBlack = Color(0xCCF5F5F5) // Used for Border color
val Black300 = Color(0xCC838B98)
val White = Color(0xCCFFFFFF)
val White400 = Color(0xCCE2E8F0)


val Yellow = Color(0xFFE8AF2F)
val Red = Color(0xCCC23729)






